services:
  - type: web
    name: fastapi-receipt-ocr
    env: python
    region: oregon  # or choose your preferred region
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
